/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { Stars, useGLTF, OrbitControls } from "@react-three/drei";
import { useSelector } from "react-redux";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Phobos.gltf");
  const {  mod } = useSelector(
    (store) => store.planets
  );
  const moonRef = useRef();

  useFrame(() => {
    moonRef.current.rotation.y += 0.001;
  });
  return (
    <>
      <Stars
        radius={500}
        depth={500}
        saturation={100}
        count={12000}
        fade={false}
        factor={2}
        enableZooms={false}
      ></Stars>

      <OrbitControls
        enableZooms={mod ? false : true}
        enablePan={false}
        enableRotate={true}
        autoRotate={false}
        screenSpacePanning={false}
      ></OrbitControls>
      <ambientLight intensity={0.8} />

      <group
        ref={moonRef}
        scale={mod ? (10 * props.radius) / 110 : 10}
        {...props}
        dispose={null}
      >
        <mesh
          geometry={nodes.phobos.geometry}
          material={materials.phobos_tex_01}
        />
      </group>
    </>
  );
}

useGLTF.preload("/Phobos.gltf");
